# hardware configuration and algorithm configuration
queue: ser
core_count: 40
node_count: 1
algorithm_preference: optuna # random_search, optuna
iter_count: 100
benchmark: HPL # HPL, HPCG

# binary path
path_to_HPL: ~/HPL/hpl-2.3/bin/Linux_Intel64/
path_to_HPCG: ~/HPCG/hpcg/build/bin/

# HPL parameter range
N: [80000, 150000]
NB: [200, 700]
PMAP: [0, 1]
PFACT: [0, 2]
NBMIN: [2, 50]
NDIV: [2, 10]
RFACT: [0, 2]
BCAST: [0, 5]
DEPTH: [0, 6]
SWAP: [0, 2]
L1: [0, 1]
U: [0, 1]
EQUIL: [0, 1]

# HPCG parameter range(both side of the bundary is included)
NX: [16, 256]
NY: [16, 256]
NZ: [16, 256]
Time: 1860