# hardware configuration and algorithm configuration
queue: ser
core_count: 40
node_count: 1
algorithm_preference: RL # random_search, optuna, RL
iter_count: 2
benchmark: HPL # HPL, HPCG

# MPI command
mpi: mpiexec.hydra

# binary path
path_to_HPL: ~/HPL/hpl-2.3/bin/Linux_Intel64/
path_to_HPCG: ~/HPCG/hpcg/build/bin/

# HPL parameter range
N: 
  range: [80000, 150000]
  step: 1
  type: int
NB: 
  range: [200, 700]
  step: 1
  type: int
PMAP: 
  range: [0, 1]
  type: categorical
PFACT: 
  range: [0, 1, 2]
  type: categorical
NBMIN: 
  range: [2, 50]
  step: 1
  type: int
NDIV: 
  range: [2, 10]
  step: 1
  type: int
RFACT: 
  range: [0, 1, 2]
  type: categorical
BCAST: 
  range: [0, 1, 2, 3, 4, 5]
  type: categorical
DEPTH: 
  range: [0, 6]
  step: 1
  type: int
SWAP: 
  range: [0, 1, 2]
  type: categorical
L1: 
  range: [0, 1]
  type: categorical
U: 
  range: [0, 1]
  type: categorical
EQUIL: 
  range: [0, 1]
  type: categorical

# HPCG parameter range(both side of the bundary is included)
NX: 
  range: [16, 256]
  step: 8
  type: int
NY: 
  range: [16, 256]
  step: 8
  type: int
NZ: 
  range: [16, 256]
  step: 8
  type: int
Time: 
  range: [1860, 1860]
  type: int